- .travis.yml
- README.md
- build.gradle
- install_core_snapshot.sh
- org.metafacture.fix.web/build.gradle
- org.metafacture.fix/build.gradle
- settings.gradle
TBH, I'm not really happy with the newly introduced metafacture-core master-SNAPSHOT dependency (6382371). What about leveraging [Gradle source dependencies](https://blog.gradle.org/introducing-source-dependencies) instead?
> Add Metafacture source dependency

- .github/workflows/publish.yml
- build.gradle
- org.metafacture.fix.ide/build.gradle
- org.metafacture.fix.web/build.gradle
- org.metafacture.fix/build.gradle
- settings.gradle
Will resolve #45 and contains other build related changes. See commits for details.
This should make the approach suggested in https://github.com/metafacture/metafacture-playground/pull/19 work (which I'll update to use `org.metafacture/metafacture-fix "0.2.0-SNAPSHOT"` after this is merged). With [OERSI consuming GitHub Packages](https://gitlab.com/oersi/oersi-etl/-/issues/59), this should allow us to get rid of the long running `oersi` branches here and in core.
> Rename group and artifact ID, update build setup

- org.metafacture.fix/build.gradle
- org.metafacture.fix/src/main/java/org/metafacture/metamorph/MetafixFilter.java
- org.metafacture.fix/src/main/resources/flux-commands.properties
- org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixFilterTest.java
Will resolve https://github.com/metafacture/metafacture-fix/issues/40
> Add MetafixFilter with fix-filter command

- build.gradle
- config/checkstyle/checkstyle.xml
- org.metafacture.fix/build.gradle
- org.metafacture.fix/src/main/java/org/metafacture/metamorph/FixBuilder.java
- org.metafacture.fix/src/main/java/org/metafacture/metamorph/Metafix.java
- org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixDslTest.java
- org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixIfTest.java
- org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixRecordTest.java
- org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixTestHelpers.java
This contains work in progress for #10 (Fix conditionals based on the Morph `<if>` construct, enabled, see `MetafixIfTest`) and #35 (record mode, disabled, see `MetafixRecordTest`).
Since metafacture-fix is work in progress in general, and this adds working if-statements for some use cases, as well as some project setup improvements (in particular for writing tests), I suggest we merge this into our main branch.
> Basic if statements and record mode draft

- .github/workflows/deploy.yml
Necessary because of renaming in metafacture/metafacture.github.io, see https://github.com/metafacture/metafacture.github.io/issues/13
> Rename destination folder for deploying IDE extensions

- config/checkstyle/checkstyle.xml
- metafix-web/src/main/java/org/metafacture/metafix/web/ServerLauncher.java
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/interpreter/FixInterpreter.java
- metafix/src/test/java/org/metafacture/metafix/InterpreterTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
> Remove Checkstyle `@SuppressWarnings`, disable for tests

- .github/workflows/build.yml
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
> Don't restrict bind scope to the bound var

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/Record.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/HashValueTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
- metafix/src/test/java/org/metafacture/metafix/RecordTest.java
Introduced concept of _virtual_ (internal) fields which can be accessed like regular metadata fields, but aren't emitted by default.
Virtual fields are emitted if
1. explicitly retained with `retain("virtual_field")`, or
2. copied with `copy_field("virtual_field", "regular_field")`, or
3. added (i.e., overwritten) with `add_field("virtual_field", "value")`.
Turned `_id` (record ID) into a virtual field. Bind scope variables are obvious candidates as well (cf. #83).
Resolves #63.
> Emit all underscore fields.

- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTest.java
> Extend Vars support.

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/HashValueTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
Delegates `Value.Hash` retrieval to `SimpleRegexTrie` for pattern matching.
All operations involving field patterns must be translated to concrete field names.
NOTE: Requires (a lot) more tests. But existing tests, including previously disabled ones, are already providing some coverage - with _trivial_ (?) modifications to make them pass (not sure why they were testing the wrong order).
Resolves #89.
> Add support for Metamorph wildcards.

- metafix/build.gradle
- metafix/src/main/java/org/metafacture/metafix/interpreter/FixInterpreter.java
- metafix/src/test/java/org/metafacture/metafix/FixParsingTest.java
- metafix/src/test/java/org/metafacture/metafix/InterpreterTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
How invested are you in the current test output? I feel, as our test suite grows, it's becoming a little unwieldy. So I'd like to propose a more compact version.
Passing:
- Before (cropped): ![passing-before](https://user-images.githubusercontent.com/20381/147222392-5469bee6-377a-446f-9ce0-73dfc57327b6.png)
- After: ![passing-after](https://user-images.githubusercontent.com/20381/147222444-4ec7b4b6-45af-42cc-990b-38dccf808d55.png)
Failing:
- Before (cropped): ![failing-before](https://user-images.githubusercontent.com/20381/147222469-74704eab-e691-4c74-b90f-a4e052284c5c.png)
- After: ![failing-after](https://user-images.githubusercontent.com/20381/147222487-f65d8d8f-3a38-4acd-b4e3-35f32b25a945.png)
> Reduce test output.

- build.gradle
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixSelectorTest.java
For Java 17 support (required in Limetrans); see eclipse/xtext#1982.
> Upgrade xtext dependency to 2.26.0.M2 (prerelease).

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
The last commit (7d9b2a4) might be debatable; but I feel making intentions explicit works in our favor for now (the usual WDCD applies, though).
Note that I deliberately went in the direction of more explicit types instead of less:
> TODO? maybe this would be a good general internal representation, resulting
> in every value being either a hash or a string, no more separate array type.
Resolves #109 and fixes most of the array issues in #100 (see 11d1e71).
> Convert marked array entity into actual array object.

- build.gradle
- metafix/build.gradle
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
- metafix/src/test/java/org/metafacture/metafix/ValueTest.java
I've opted for the non-destructive approach w.r.t. `Value`s. I don't think we're consistent as to when we modify an existing value and when we create a new one. Let me know if you have a preference - or if I'm mistaken and there's indeed a system to it ;)
Omitted Fix functions from the [cheat sheet](https://librecat.org/assets/catmandu_cheat_sheet.pdf):
* `assoc()`
* `diassoc()`
* `compact()` (not applicable)
* `flatten()`
* `from_json()`
* `to_json()`
* `uri_decode()`
* `uri_encode()`
Resolves #100.
> Add Fix functions from Catmandu Cheat Sheet.

- metafix/src/main/java/org/metafacture/metafix/FixConditional.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
NOTE: There's a (minor) compatibility break in `MetafixRecordTest.reject()`.
Resolves #117.
> Fix `exists()` Fix conditional with nested paths.

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
Resolves #106.
Notable behaviour changes w.r.t. unmarked arrays:
- Array to string: [`format`](https://github.com/metafacture/metafacture-fix/pull/131/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7L249-R245), [`join_field`](https://github.com/metafacture/metafacture-fix/pull/131/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7L809-R797)
- String to array: [`parse_text`](https://github.com/metafacture/metafacture-fix/pull/131/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7L266-R262), `split_field` ([1](https://github.com/metafacture/metafacture-fix/pull/131/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7L1533-R1507), [2](https://github.com/metafacture/metafacture-fix/pull/131/file …
> Emit indexed arrays only if marked.

- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
Resolves #115 and #119.
NOTE: The updated test `MetafixRecordTest.appendWithAsteriksWildcardAtTheEnd()` was probably wrong in the first place; the original [comment](https://github.com/metafacture/metafacture-fix/issues/89#issuecomment-999433570) expected the other values as well, but the actual [review](https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/master/data/approved/wildCardTest/expected_test6.json#L13) (which was the basis for the unit test) did not.
> Fix path wildcards in combination with arrays.

- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/resources/org/metafacture/metafix/fixes/filemap.fix
- metafix/src/test/resources/org/metafacture/metafix/fixes/filemap_lookup.fix
Allows file maps to be referenced relative to Fix file (see #12 for the introduction of this mechanism in the context of the `include()` function).
> Apply relative path "magic" to file maps.

- build.gradle
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixSelectorTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixToDo.java
Since we're keeping quite a few disabled tests in stock that indicate pending work (which is a good thing), it's not always clear (to me, at least) when any of those tests might be resolved due to (seemingly unrelated) fixes. So I'd like to propose a new `@MetafixToDo` annotation instead of the current `@Disabled` annotation, which takes care of reminding us of no longer failing tests: Failing tests marked as "to do" will be reported as *skipped* (just as before¹); passing tests marked as "to do" will be reported as *failed* (so we know we can remove the annotation).
¹ Except not quite: One problem with the proposed approach is that the log messages of still failing tests somewhat clutter the test output. We could reduce the log level for tests to `ERROR` as a remedy. OTOH, it's not …
> Introduce `@MetafixToDo` annotation to mark tests as disabled.

- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
Metamorph does this with any map (including external file maps) in `<lookup>`, while Catmandu doesn't have a concept of _named_ internal maps.
So the middle ground here is to apply a heuristic for determining whether an internal or an external file map was probably referenced.
> Ignore unknown internal maps in `lookup()` Fix function.

- .editorconfig
- .gitignore
- build.gradle
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfStrings/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/set_arrayIntoArray/expected.json
`editorconfig-gradle-plugin` doesn't have sufficient [support for `.editorconfig` properties](https://github.com/ec4j/editorconfig-gradle-plugin#how-it-works).
`editorconfig-checker` has been added in version [2.4.0](https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.4.0) for linux amd64.
> Include `editorconfig-checker` to complement `editorconfig-gradle-plugin`.

- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithAsteriskArrayWildcard/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithAsteriskArrayWildcard/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithAsteriskArrayWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithAsteriskArrayWildcard/test.flux
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithAsteriskArrayWildcard/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithAsteriskArrayWildcard/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithAsteriskArrayWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithAsteriskArrayWildcard/test.flux
I needed a test to check if asterisk is working with `append`/`prepend` in array of objects in context of OERSI. So I created an additional integration test.
> Add additional append prepend test

- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldkIntoArrayOfObjectsWithLastWildcard/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldkIntoArrayOfObjectsWithLastWildcard/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldkIntoArrayOfObjectsWithLastWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldkIntoArrayOfObjectsWithLastWildcard/test.flux
#102
Behaviour seems to have changed #102 breaks and master ingores
if there is no object in the array and you use to `add_field` with
`$last` wildcard
> Add integration test for `add_field` with `$last` wildcard

- .gitignore
- metafix/build.gradle
- metafix/integrationTest.sh
- metafix/src/main/java/org/metafacture/metafix/FixProcessException.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnExecutionException/expected.err
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnExecutionException/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnExecutionException/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnExecutionException/test.flux
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnProcessException/expected.err
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnProcessException/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnProcessException/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnProcessException/test.flux
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipExpressionOnExecutionException/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipExpressionOnExecutionException/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipExpressionOnExecutionException/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipExpressionOnExecutionException/test.flux
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipRecordOnExecutionException/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipRecordOnExecutionException/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipRecordOnExecutionException/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessSkipRecordOnExecutionException/test.flux
Resolves #192.
Levels of strictness:
- `PROCESS`: Abort process by throwing an exception. This is the current behaviour and the new default.
- `RECORD`: Ignore (skip) failed record and log an error.
- `EXPRESSION`: Ignore (skip) failed expression and log a warning.
Introduces `FixProcessException` to differentiate from `FixExecutionException`: The latter indicating potentially data-dependent issues that should be subject to strictness handling, while the former should only refer to static issues with the usage of Fix expressions.
Areas for future work:
- Escalation strategy: Once `n` expressions have failed, fail the record; once `n` records have failed, fail the process.
- Possibly Fix-internal configuration mechanism (#59).
- Expression grouping ([`maybe()` …
> Implement "strict" mode.

- metafix/src/main/java/org/metafacture/metafix/FixBind.java
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/main/java/org/metafacture/metafix/api/FixContext.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/util/TestContext.java
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/strictnessAbortProcessOnProcessException/expected.err
Everything that is data-independent should be done only once at initialization time. IOW: Perform as little work as possible per record.
Behaviour changes:
1. Records are modified in-place instead of passing around and replacing (shallow) copies of records. Doesn't seem to have any practical consequences, though.
2. Fix definitions are interpreted at initialization time, thus potentially throwing exceptions immediately instead of later during record processing. Effect can be observed in integration test `script/fromJson/toJson/strictnessAbortProcessOnProcessException`.
Initial measurements indicate a speedup of about 10 % with a sufficiently complex mapping; more benchmark results ~~to be added later (@fsteeg: But you can already review the technical details if you like)~~ below.
Related …
> Separate Fix expression interpretation from record data transformation.

- metafix/src/main/java/org/metafacture/metafix/FixPath.java
- metafix/src/test/java/org/metafacture/metafix/HashValueTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithFirstArrayWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithFirstArrayWildcard/todo.txt
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithLastArrayWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/appendArrayOfObjectsWithLastArrayWildcard/todo.txt
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithFirstArrayWildcard/todo.txt
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithLastArrayWildcard/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/prependArrayOfObjectsWithLastArrayWildcard/todo.txt
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/todo.txt
Resolves #135, resolves #144.
Contains some potential performance improvements (e.g. 5d3168e3e73897350eaf00165488ebeaa687bbfe), simple tests with 10k records in limetrans (`./gradlew -Dhbz.limetrans.type=fix testAlmaHBZ`) seem to point to a slight improvement (5-10%).
>  Handle $first, $last for find and replace in arrays (#135, #144)

- metafix/src/main/java/org/metafacture/metafix/Value.java
Matching path wildcard patterns against record fields is still a major bottleneck (see [#207 (comment)](https://github.com/metafacture/metafacture-fix/issues/207#issuecomment-1106645612) for the latest analysis and 90cbde4 for the preceding optimization). We can save a considerable amount of CPU time (with a complex real-world mapping) by simply skipping the pattern matching process for literal (i.e., non-wildcard) field names.
NOTE: Runs potential risk of diverging from `WildcardTrie`/`SimpleRegexTrie` implementation.
Related to #207.
---
Benchmark results:
| Alma records        | Runtime @ 1933b59 | Runtime @ f64cbde |   Boost |
|:--------------------|------------------:|------------------:|--------:|
| 3.5k                |               40s |               22s | -46.14% |
| 1.6m (out …
> Optimize path wildcard matching for literal (non-wildcard) field names.

- build.gradle
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
Resolves #147, see [Playground example](https://test.metafacture.org/playground/?flux=PG_DATA%0A%7Cdecode-xml%0A%7Chandle-generic-xml%0A%7Cfix%28%22nothing%28%29%22%2CrepeatedFieldsToEntities%3D%22true%22%29%0A%7Cflatten%0A%7Cencode-literals%0A%7Cprint%0A%3B&data=%3C%3Fxml+version%3D%221.0%22%3F%3E%0A%3Crecord%3E%0A++++%3Cfield%3Ea%3C/field%3E%0A++++%3Cfield%3Eb%3C/field%3E%0A%3C/record%3E).
> Add option to emit repeated fields as entities (#147)

- metafix/src/main/java/org/metafacture/metafix/Fix.xtext
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
`Value.Hash`:
- Avoid `Stream` API in hot path.
- Sidestep `WildcardTrie` w.r.t. alternations.
- Guard `SimpleRegexTrie` matching with prefix match.
`RecordTransformer`:
- Extract option building out of the record loop.
- Only resolve variables if actually needed.
This is getting considerably more complex. But the expected speedup is nothing to scoff at either: up to 20 % in real-world scenarios and even up to 80 % in synthetic benchmarks.
NOTE: Adding options to conditionals (see 56e59e6) is orthogonal to the performance optimizations and entirely optional. It just came naturally and simplified the implementation a little.
Related to #207.
[Next up: `Value.TypeMatcher`. While it sure does provide a nice API, it's the top offender now (fills whole top 10 in HPROF CPU profile).]
--- …
> Optimize performance bottlenecks in `Value.Hash` and `RecordTransformer`.

- README.md
- metafix/src/main/java/org/metafacture/metafix/FixBind.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/resources/org/metafacture/metafix/fixes/once.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/onceSimple/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/onceSimple/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/onceSimple/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/onceSimple/test.flux
Allows to perform setup tasks that don't have to (and/or should not) be repeated for each record. In Limetrans we implemented it as a [custom Fix bind](https://github.com/hbz/limetrans/blob/55da0b6c1a706854637a755caa94e27aacfa8a6e/src/main/java/hbz/limetrans/function/Once.java) (cf. #124), but maybe it's useful generally.
Open question: Currently, the scope is per Fix invocation. Should it be per Fix _file_ instead? (Then we would change `shouldExecuteOnlyOncePerFixInstance()` to `shouldExecuteOnlyOncePerFixFile()`.)
@TobiasNx: Do you also want to do a functional review?
> Add `once()` Fix bind.

- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/FixPath.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/Record.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/RecordTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromXml/toJson/lookupInDeeplyNestedArrayOfObjects/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromXml/toJson/lookupInDeeplyNestedArrayOfObjects/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromXml/toJson/lookupInDeeplyNestedArrayOfObjects/todo.txt
Append to path when adding values, set base path for nested values.
This seems to resolves the issue in hbz/lobid-resources#1354, see unit and integration tests, which are now passing, but tweaked (unit test for output structure, integration test for field order).
> Remove path replacement workarounds, only set and append paths

- README.md
- metafix/src/main/java/org/metafacture/metafix/FixBind.java
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
Ports Metamorph [macros](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#defining-macros) to Metafix.
Open questions:
- Should the function be named `call_macro()` instead?
- Should calling an unknown macro throw an exception?
> Add `put_macro()`/`call_macro()` Fix bind and function.

- metafix/src/main/java/org/metafacture/metafix/FixConditional.java
- metafix/src/main/java/org/metafacture/metafix/api/FixPredicate.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
Complements path/string (`any_*()`) and path/path (`in()`) conditionals with string/string variants.
Particular useful in combination with local variables in `macro()` (#243) or `include()` (#245).
_Base branch will be changed automatically once #243 is merged._
> Add `str_contain()`/`str_equal()`/`str_match()` Fix conditionals.

- README.md
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/api/FixFunction.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/flatten/todo.txt
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/flattenNested/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/flattenNested/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/flattenNested/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/flattenNested/test.flux
Implements Catmandu's [`flatten()`](https://metacpan.org/pod/Catmandu::Fix::flatten) function.
Resolves #122.
> Add `flatten()` Fix function.

- README.md
- metafix/build.gradle
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/JsonValue.java
- metafix/src/main/java/org/metafacture/metafix/Record.java
- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
Open questions:
1. `shouldConvertNullFromJson()` seems counterintuitive; but fixing it would require changing the behaviour of `Record.transform(String, BiConsumer)`. Also, we'd have to differentiate between value being `null` and `error_string` being `null`. One option might be to generate an empty string which could then get at least cleaned up by `vacuum()`.
2. `to_json()` error behaviour is untested; I have no idea how to conjure up an invalid object ;)
3. Should we somehow utilize JsonDecoder/JsonEncoder instead of interacting with Jackson directly? Would certainly allow for greater compatibility/configurability.
@TobiasNx: Do you also want to do a functional review?
> Add `from_json()`/`to_json()` Fix functions.

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpperStrictnessHandlesProcessExceptions/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpperStrictnessHandlesProcessExceptions/input.xml
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpperStrictnessHandlesProcessExceptions/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpperStrictnessHandlesProcessExceptions/test.flux
Allows to subject `FixProcessException`s to the same treatment as `FixExecutionException`s.
I.e., when `strictness` is set and `strictnessHandlesProcessExceptions` is not, it only handles `FixExecutionException`s; when `strictnessHandlesProcessExceptions` is set _in addition_ to `strictness`, it handles `FixExecutionException`s _and_ `FixProcessException`s.
Related to #251.
> Optionally apply "strict" mode to `FixProcessException`s.

- metafix/src/main/java/org/metafacture/metafix/FixBind.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
Every time a macro is (re-)declared (e.g., for each record), its "static" local variables (options) are added to an internal list. So this list grows with each record and merging it (`RecordTransformer.getVars()`) takes longer and longer.
Instead, keep track of each type of variables (global, static, dynamic) separately and replace already existing variables of the same type.
Resolves #258.
> Fix macro performance regression.

- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/resources/org/metafacture/metafix/fixes/macro.fix
When a statement inside a macro fails, it's hard to find the actual call site. Provide the caller location for easier debugging.
Open question:
- Should the introductory phrase (`Error while ...`) be included for every item in the stack? Or should we build the combined message differently?
Related to #123 and #243.
> Include caller location and text in macro execution exception.

- metafix/src/main/java/org/metafacture/metafix/Value.java
- metafix/src/test/java/org/metafacture/metafix/HashValueTest.java
Data structures in `Value.Hash.findFields(String, Set<String>)` are not safe to use across multiple threads. Switch to thread-local variables instead.
Resolves #255.
> Make `Value.Hash.findFields()` thread-safe with thread-local variables.

- metafix/build.gradle
It appears that sbt resolves to a newer version (2.28.0) than Maven/Gradle (2.20.0), which might cause some confusion in Xtext EMF registration.
Resolves hbz/lobid-resources#1462.
> Fix `NoSuchFieldError` in lobid-resources web app.

- README.md
- build.gradle
- metafix-runner/build.gradle
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/main/java/org/metafacture/metafix/api/FixFunction.java
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupSimpleWithMultiColumnFile/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupSimpleWithMultiColumnFile/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupSimpleWithMultiColumnFile/mapfile.tsv
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupSimpleWithMultiColumnFile/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupSimpleWithMultiColumnFile/test.flux
WIP until a stable metafacture-core release artifact becomes available.
Resolves #265.
> Add `FileMap` options to `put_filemap()` Fix function.

- metafix-vsc/fix.configuration.json
- metafix-vsc/fix.tmLanguage
- metafix-vsc/package.json
Update vsc extension to match the current fix implementation.
- update highlighting of fix methods, fix conditionals and fix binds. Resolves #291 
- update line comments (#), remove wrong block comments. Resolves #4 and resolves #129
> Update vsc extension to new fix

- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/resources/org/metafacture/metafix/fixes/include.fix
- metafix/src/test/resources/org/metafacture/metafix/fixes/nested.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldSimpleDestructive/todo.txt
Resolves (part of) #116.
NOTE: `add_field()` and `set_field()` are now equivalent, but according to [Catmandu's documentation](https://metacpan.org/pod/Catmandu::Fix::set_field) `set_field()` "will not create the intermediate structures if they are missing". (Opened #309 for this.)
> Change `add_field()` Fix function to destructive behaviour for Catmandu compatibility.

- README.md
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
Use metamorph's URLEncoder for uri_encode.
Supersedes https://github.com/metafacture/metafacture-fix/pull/285.
> Add uri_encode (#273)

- README.md
- metafix-vsc/package.json
> Add hint to README regarding problems when build on Windows

- README.md
- build.gradle
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
See  metafacture/metafacture-fix#273.
- introduce options "safe_chars" and "plus_for_space" for function "uri_encode"
- update README
- bump metafacture dependency to 5.7.0-rc2
> Fix function "uri_encode" to be backwards compatible

- README.md
Add links in docu to playground examples for several fixes. More examples can be added later.
> Add links to  playground for several fixes

- metafix-web/src/main/java/org/metafacture/metafix/web/FixServlet.java
- metafix/src/jmh/java/org/metafacture/metafix/MetafixBenchmark.java
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/main/java/org/metafacture/metafix/MetafixStreamAnalyzer.java
- metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
- metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java
See metafacture/metafacture-core#514.
> Close resources.

- build.gradle
- gradle/source-layout.gradle
- metafix-ide/build.gradle
- metafix/build.gradle
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToArrayOfStringsWithIndex/expected.err
- settings.gradle
Follow-up to #341.
There's one more warning when running the `jmh` task:
> Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.6/userguide/upgrading_version_7.html#task_project
Should be fixed by melix/jmh-gradle-plugin#261, but hasn't been released yet.
> Provide Gradle 9 forward compatibility.

- build.gradle
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToArrayOfStringsWithIndex/expected.err
Resolves #343.
Consumes the rc from metafacture-core which also uses java 11. 
(See https://github.com/metafacture/metafacture-core/issues/515).
> Bump java version from 8 to 11

- README.md
Since all fixes are in one of three Java Classes I created a workaround to link to the Java Code using the GitHub search.
@maipet could you have a look if this meets your demands?
@blackwinter could you have a look if this is okay for you?
> Add a workaround to link to Java Code

- README.md
- metafix/src/main/java/org/metafacture/metafix/FindFixPaths.java
- metafix/src/test/java/org/metafacture/metafix/FindFixPathsTest.java
See #347
@fsteeg as author of the `list-fix-paths` and `list-fix-value` wrappers could you review this new wrapper for finding the paths/keys to given value-patterns.
> Add draft for new find fix paths modul #347

- metafix/src/main/java/org/metafacture/metafix/FindFixPaths.java
- metafix/src/test/java/org/metafacture/metafix/FindFixPathsTest.java
> Delete escape signs in default template for find-fix-paths #347

- README.md
- metafix/src/main/java/org/metafacture/metafix/FixMethod.java
- metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
> Add new fix method to set variable with element value #282

- README.md
- metafix-runner/build.gradle
- metafix/src/main/resources/log4j.xml
Enables java logging. The log level can be changed by setting a variable. Set and run like this:
JAVA_OPTS="-Dorg.metafacture.metafix.logLevel=DEBUG"; ./gradlew installDist;  cd metafix-runner/build/install/metafix-runner; bin/metafix-runner $pathTo.flux
See #383.
Substitutes #387.
> Add log4j logging

- metafix-runner/build.gradle
- metafix/integrationTest.sh
- metafix/src/main/java/org/metafacture/metafix/Metafix.java
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/maxEntityCount/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/maxEntityCount/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/maxEntityCount/metafix.args
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/maxEntityCount/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/maxEntityCount/test.flux
_Just a proof-of-concept to gauge interest in such a feature; the immediate need has been rendered moot (due to the record's holdings being suppressed from publishing now)._
This is a brute-force approach to dealing with OOM situations when Alma records have an excessive number of items (e.g. [99374518570506441](https://lobid.org/resources/99374518570506441): >12000 entities = ~10 GB heap for the Record instance). Loosely modeled after JAXP's [`totalEntitySizeLimit`](https://docs.oracle.com/en/java/javase/13/security/java-api-xml-processing-jaxp-security-guide.html#GUID-82F8C206-F2DF-4204-9544-F96155B1D258__TABLE_RQ1_3PY_HHB), except that we don't abort processing but instead skip the remaining entities.
~Use Metafix instance setter `setMaxEntityCount(int)` or~ set system property …
> Optionally specify limit for number of entities in a record.

- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValueAsIndexedRepeatedField/expected.json
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValueAsIndexedRepeatedField/input.json
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValueAsIndexedRepeatedField/test.fix
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValueAsIndexedRepeatedField/test.flux
- metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValueAsIndexedRepeatedField/todo.txt
Adds integration test for #239 
It copies an single value array of strings and outputs it as indexed repeated field to show the problematic internal handling that is otherwise [disguised](https://github.com/metafacture/metafacture-fix/blob/d4cd18c7c39384a5596a689f22daaa6117be7f64/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfStringsWithSingleValue).
> Add integration test for #239
