metafacture/metafacture-fix

README.md, org.metafacture.fix.parent/org.metafacture.fix.web/build.gradle, org.metafacture.fix.parent/org.metafacture.fix.web/src/main/java/org/metafacture/fix/web/FixServlet.xtend, org.metafacture.fix.parent/org.metafacture.fix.web/src/main/java/org/metafacture/fix/web/ServerLauncher.xtend, org.metafacture.fix.parent/org.metafacture.fix.web/src/main/webapp/index.html, org.metafacture.fix.parent/org.metafacture.fix.web/src/main/webapp/style.css, org.metafacture.fix.parent/org.metafacture.fix/src/main/java/org/metafacture/metamorph/Metafix.java
Will resolve https://github.com/metafacture/metafacture-fix/issues/1
See http://test.lobid.org/fix
@dr0i: Since we don't have a production deployment for this yet, you can merge after review.
=> Enable running workflows in the web UI

org.metafacture.fix/src/main/java/org/metafacture/fix/Fix.xtext, org.metafacture.fix/src/main/java/org/metafacture/metamorph/FixBuilder.java, org.metafacture.fix/src/main/java/org/metafacture/metamorph/FixFunction.java, org.metafacture.fix/src/main/java/org/metafacture/metamorph/Metafix.java, org.metafacture.fix/src/main/resources/flux-commands.properties, org.metafacture.fix/src/test/java/org/metafacture/metamorph/MetafixDslTest.java, org.metafacture.fix/src/test/java/org/metafacture/metamorph/maps/test.csv, org.metafacture.fix/src/test/java/org/metafacture/metamorph/maps/test.tsv
This is the current state of the Fix language implementation from the `oersi` branch (see https://github.com/metafacture/metafacture-core/pull/329/files), without anything oersi-specific or the new work on the Fix language server and extension by @katauber. Things are getting a little messy with the `oersi` branch being required for creating a Fix extension that actually works with the oersi workflows, so I think this is a good time to bring over the current state of the actual Fix implementation to master.
@blackwinter Would be great if you could take a look. It's a big diff, so this is probably not really a pleasure to review. I should have never let this branch diverge so much. It's all work in progress though, so it might make sense to improve this after merging, in additional issues, …
=> Current state of Fix implementation

org.metafacture.fix.vsc/package.json
I missed to increase the version of the extension. A extension can only be published with a higher version.
=> Increase extensions version.

README.md
Complements Github Actions migration.
See https://github.com/hbz/lobid/issues/433.
=> Add workflow badge "Build and Deploy"

org.metafacture.fix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
And a little cleanup of unused parameters.
Will resolve #68.
=> Add test for null field behavior

.github/workflows/deploy.yml
=> Fix VS Extension build

metafix/src/main/java/org/metafacture/metafix/Value.java, metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
=> Insert into referenced elements using $first, $last, index

metafix/src/main/java/org/metafacture/metafix/Value.java, metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java
=> Extend `vacuum()` Fix function.

metafix/src/main/java/org/metafacture/metafix/Fix.xtext, metafix/src/main/java/org/metafacture/metafix/FixBind.java, metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java, metafix/src/main/java/org/metafacture/metafix/api/FixContext.java, metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java, metafix/src/test/java/org/metafacture/metafix/util/TestContext.java, metafix/src/test/java/org/metafacture/metafix/util/TestFunction.java
=> Allow custom Java contexts to be called from Fix.

metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java, metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java, metafix/src/test/resources/org/metafacture/metafix/fixes/base.fix, metafix/src/test/resources/org/metafacture/metafix/fixes/include.fix, metafix/src/test/resources/org/metafacture/metafix/fixes/nested.fix, metafix/src/test/resources/org/metafacture/metafix/fixes/var.fix
Resolves #12.
_Base branch will be changed automatically once #124 is merged._
=> Add `include()` Fix function.

metafix/src/main/java/org/metafacture/metafix/FixBind.java, metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/main/java/org/metafacture/metafix/FixPath.java, metafix/src/main/java/org/metafacture/metafix/Path.java, metafix/src/main/java/org/metafacture/metafix/Value.java, metafix/src/main/java/org/metafacture/metafix/api/FixPredicate.java, metafix/src/test/java/org/metafacture/metafix/util/TestContext.java, metafix/src/test/java/org/metafacture/metafix/util/TestFunction.java
As discussed in our meeting, this is an interim state for #102.
=> Extract FixPath logic from Value

metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/main/java/org/metafacture/metafix/FixParseException.java, metafix/src/main/java/org/metafacture/metafix/FixStandaloneSetup.java, metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/main/java/org/metafacture/metafix/validation/XtextValidator.java, metafix/src/test/java/org/metafacture/metafix/MetafixTest.java, metafix/src/test/resources/org/metafacture/metafix/fixes/invalid.fix
=> Throw exception for invalid Fix files.

metafix/src/main/java/org/metafacture/metafix/FixExecutionException.java, metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/main/java/org/metafacture/metafix/FixStandaloneSetup.java, metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java, metafix/src/main/java/org/metafacture/metafix/Value.java, metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java, metafix/src/test/java/org/metafacture/metafix/MetafixTestHelpers.java, metafix/src/test/resources/org/metafacture/metafix/fixes/error.fix
=> Include location and text in Fix execution exception.

metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAsteriskIntoArrayOfObjects/disabled.txt, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAsteriskIntoArrayOfObjects/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAsteriskIntoArrayOfObjects/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAsteriskIntoArrayOfObjects/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAsteriskIntoArrayOfObjects/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAsteriskIntoArrayOfObjects/disabled.txt, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAsteriskIntoArrayOfObjects/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAsteriskIntoArrayOfObjects/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAsteriskIntoArrayOfObjects/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAsteriskIntoArrayOfObjects/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAsteriskIntoArrayOfObjects/disabled.txt, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAsteriskIntoArrayOfObjects/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAsteriskIntoArrayOfObjects/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAsteriskIntoArrayOfObjects/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAsteriskIntoArrayOfObjects/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/set_arrayIntoArray/disabled.txt
=> Add integration test for #156

metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listArrayOfObjectsAndMoveSubfield/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listArrayOfObjectsAndMoveSubfield/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listArrayOfObjectsAndMoveSubfield/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listArrayOfObjectsAndMoveSubfield/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield/todo.txt
Spottet this while working on OERSI.
=> Add integration tests for #113

metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/main/java/org/metafacture/metafix/RecordTransformer.java, metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java, metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/put_varsUsedInOption/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/put_varsUsedInOption/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/put_varsUsedInOption/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/script/fromJson/toJson/put_varsUsedInOption/test.flux
=> Resolve variables in options.

metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInSubfieldOfArrayOfObjectsWithLastWildcard/todo.txt
Found one additional error in oersi.
But this seems to be a change not connected to #102.
=> Add integration test for replace with last Wildcard (#102)

metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToArrayOfStringsWithIndex/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToArrayOfStringsWithIndex/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToArrayOfStringsWithIndex/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndex/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndex/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndex/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndexGeneratingNewObject/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndexGeneratingNewObject/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndexGeneratingNewObject/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldToSubfieldOfArrayOfObjectsWithIndexGeneratingNewObject/test.flux
=> Update integration test for copying with index-nr

README.md, metafix/src/main/java/org/metafacture/metafix/FixConditional.java, metafix/src/test/java/org/metafacture/metafix/MetafixIfTest.java, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInArrayOfStrings/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInArrayOfStrings/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInArrayOfStrings/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInArrayOfStrings/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInSimpleField/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInSimpleField/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInSimpleField/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/ifInSimpleField/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInArrayOfStrings/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInArrayOfStrings/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInArrayOfStrings/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInArrayOfStrings/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInSimpleField/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInSimpleField/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInSimpleField/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/conditional/fromJson/toJson/unlessInSimpleField/test.flux
=> Add `in()` Fix conditional.

README.md, metafix/src/main/java/org/metafacture/metafix/FixBind.java, metafix/src/test/java/org/metafacture/metafix/MetafixBindTest.java, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listAsSimple/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listAsSimple/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listAsSimple/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/bind/fromJson/toJson/listAsSimple/test.flux
=> Add `list_as()` Fix bind.

metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping_2/expected.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping_2/input.json, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping_2/test.fix, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping_2/test.flux, metafix/src/test/resources/org/metafacture/metafix/integration/method/fromJson/toJson/replace_allInPastedSubfieldOfArrayOfObjectsWithAsteriskWithGrouping_2/todo.txt
=> Add integration test for #278

metafix/src/main/java/org/metafacture/metafix/FixBind.java, metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/main/java/org/metafacture/metafix/FixPath.java, metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
=> Fix issues caused by incomplete value paths

MAINTAINING.md, README.md, build.gradle
=> Switch to next dev version, add instructions on releasing

build.gradle
=> Update to latest metafacture-core release candidate 

README.md, metafix/src/main/java/org/metafacture/metafix/Metafix.java, metafix/src/test/java/org/metafacture/metafix/MetafixLookupTest.java
In favor of #316.
Resolves #301.
Complies with metafacture-core.
- disable ClassDataAbstractionCoupling checkstyle in Metafix
- implement test
- update README
=> Allow lookup on URLs (#301)

metafix-vsc/fix.snippets.json, metafix-vsc/package.json
=> Add extension snippets for all do binds

README.md
=> Add how to execute a flux via CLI

README.md, metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java
=> Add to_base64 function #354

README.md, build.gradle, metafix/build.gradle, metafix/src/main/java/org/metafacture/metafix/FixMethod.java, metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java
=> Add log function

metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/set_arrayWithoutValuesAndMove_fieldNewArrayOfStringsIntoArrayOfObjects/test.fix
https://github.com/metafacture/metafacture-fix/pull/376#issuecomment-2416642523
=> Change set_array specific test back #127
